#Note: delete extra ~empty rows from ecoevo_jobs before importing
#Note: save-as UTF-8 csv before importing

jobs <- list(
  faculty = readxl::read_excel("./data-raw/ecoevojobs 22-23.xlsx", sheet = 1),
  postdoc = readxl::read_excel("./data-raw/ecoevojobs 22-23.xlsx", sheet = 2))
jobs <- lapply(jobs, 
               FUN = function(x) {colnames(x) <- x[1, ]; x <- x[-1, ]; return(x)})
jobs <- lapply(jobs, FUN = function(x) {return(x[!is.na(x$Timestamp), ])})

#Read in Carnegie data sheet
carnegie_val <- 
  readxl::read_excel("./data-raw/CCIHE2021-PublicData.xlsx", sheet = "Values")
colnames(carnegie_val) <- c("Variable", "Label", "Value", "Value_Label")
carnegie_val <- carnegie_val[!is.na(carnegie_val$Value_Label), ]

fill_vals <- function(x) {
  if(is.na(x[1])) {stop("first value must not be NA")}
  for (i in 1:length(x)) {if(is.na(x[i])) {x[i] <- x[i-1]}}
  return(x)
}
carnegie_val$Variable <- fill_vals(carnegie_val$Variable)
carnegie_val$Label <- fill_vals(carnegie_val$Label)

carnegie_val <- dplyr::filter(carnegie_val,
                              !Variable %in% c("Basic2000", "BASIC2005",
                                               "BASIC2010", "BASIC2015",
                                               "BASIC2018"))
#Label R1 and R2
carnegie_val <- dplyr::mutate(
  carnegie_val,
  Value_Label = ifelse(Variable == "BASIC2021",
                       ifelse(Value == 15,
                              paste("R1", Value_Label),
                              ifelse(Value == 16,
                                     paste("R2", Value_Label),
                                     Value_Label)),
                       Value_Label))


carnegie_dat <- 
  readxl::read_excel("./data-raw/CCIHE2021-PublicData.xlsx", sheet = "Data")
carnegie_dat <- dplyr::select(carnegie_dat,
                              !c(basic2000, basic2005, basic2010,
                              basic2015, basic2018))

                              
##STOPPED here


##TODO: add state matching for same-name schools, like Marian University
##      or Wheaton College

#Pull in the school insti_rankings into the Jobs sheet
jobs$insti_ranking <- carnegie$insti_ranking[match(jobs$Institution, carnegie$NAME)]

#Flag international schools
jobs$insti_ranking[!jobs$Location %in% 
                     c(state.name, "District of Columbia", "USA")] <-
  "International"

#Check that international flags don't have any false positives
table(jobs$Location[jobs$insti_ranking == "International"])

#Print institutions with no successful match 
unique(jobs$Institution[is.na(jobs$insti_ranking)])

#Rules to add for incomplete matching
#Treat "The" from beginning of Carnegie as optional
#Treat " at " anywhere in Carnegie as optional
#Carnegie uses "-" with no spaces, ecoevo sometimes uses ", " or " " or " - "

#Change all "St" and "St." to be "Saint" for matching as well

names_mod <- trimws(gsub("^The |, | at |-| - ", " ",
                         gsub("St |St\\. ", "Saint ", carnegie$NAME)))
insti_mod <- trimws(gsub("^The |, | at |-| - ", " ",
                         gsub("St |St\\. ", "Saint ", jobs$Institution)))

##Do partial matching
#Save the partially matched names to enable double-checking
jobs$matched_insti <- NA
jobs$matched_insti[is.na(jobs$insti_ranking)] <- 
  carnegie$NAME[match(insti_mod[is.na(jobs$insti_ranking)], names_mod)]

#Save the rankings with partial matching
jobs$insti_ranking[is.na(jobs$insti_ranking)] <- 
  carnegie$insti_ranking[match(insti_mod[is.na(jobs$insti_ranking)], names_mod)]

unmatched_names <- unique(jobs$Institution[is.na(jobs$insti_ranking)])

#Update manually-curated aliases list
#Original alias list generated by running:
# aliases <- data.frame("ecoevo_names" = unmatched_names, 
#                       "carnegie_names" = NA, "checked" = "N")
aliases <- read.csv("aliases.csv", fileEncoding = "Windows-1252")
if(any(!unmatched_names %in% aliases$ecoevo_names)) {
  aliases <- 
    rbind(aliases,
          data.frame(
            "ecoevo_names" = 
              unmatched_names[!unmatched_names %in% aliases$ecoevo_names],
            "carnegie_names" = NA, "checked" = "N"))
}
aliases <- aliases[order(aliases$ecoevo_names), ]
write.csv(x = aliases, file = "aliases.csv", row.names = FALSE,
          fileEncoding = "Windows-1252")
#Update then save as UTF-8

#Match using aliases     
myrows <- which(is.na(jobs$insti_ranking))
jobs$insti_ranking[myrows] <- 
  carnegie$insti_ranking[
    match(
      x = aliases$carnegie_names[
        match(jobs$Institution[myrows], aliases$ecoevo_names)],
      table = carnegie$NAME)]

write.csv(jobs, "jobs_withrankings.csv", row.names = FALSE)

##Old code below:


#Note: some schools will need aliases, bc carnegie lists them as
# with a name when they are the main campus (e.g. U of M is
# "University of Minnesota-Twin Cites")



# #For non-exact matches, find closest named university
# jobs$matched_insti <- NA
# for (row in which(is.na(jobs$insti_ranking))) {
#   state <- state.abb[match(jobs$Location[row], state.name)]
#   jobs$matched_insti[row] <- carnegie$NAME[which(carnegie$STABBR == state)][
#     stringdist::amatch(method = "lcs",
#       jobs$Institution[row],
#       carnegie$NAME[which(carnegie$STABBR == state)], 
#       maxDist = 20)]
# }
# 
# #Still struggling to find good weights that will be happy to drop endings
# carnegie$NAME[which(carnegie$STABBR == "OR")]
# stringdist::stringdist("Oregon State",
#                        "Oregon State University",
#                        weight = c(d = .001, i = .1, s = .1, t = 1))
# stringdist::stringdist("Oregon State",
#                        "Reed College",
#                        weight = c(d = .001, i = .1, s = .1, t = 1))
# carnegie$NAME[which(carnegie$STABBR == "OR")][stringdist::amatch("Oregon State",
#                    carnegie$NAME[which(carnegie$STABBR == "OR")],
#                        weight = c(d = .001, i = .1, s = .1, t = 1),
#                    maxDist = 100)]

##TODO: adjust non-exact matching to weight deletions (from the ecoevo list string)
##       to be 0 penalty

# 
# jobs$stringdist <- NA
# for (row in which(is.na(jobs$insti_ranking))) {
#   jobs$matched_insti[row] <- carnegie$NAME[
#     stringdist::amatch(jobs$Institution[row], carnegie$NAME, maxDist = 20)]
# }

# tail(unique(jobs$Institution[is.na(jobs$insti_ranking)]), 15)
# 
# table(jobs$Location[is.na(jobs$insti_ranking)])
# table(jobs$Rank)
# 
# write.csv(jobs, file = "jobs_output.csv", row.names = F)


#Add in aliases
# aliases <- c("MIT" = "Massachusetts Institute of Technology",
#              "UT Austin" =
#              
# 
# cutoffs <- c("Cal State" = "California State University",
#              "UMass" = "University of Massachusetts",


# MIT
# Cal State Fullerton
# UMass Boston
# UT Austin
# University of North Carolina
# UCLA
# University of Washington (point to Seattle)
# Western Colorado University
# The Ohio State University (point to main campus)
# NC State University
# UC Davis
# UCSB
# UNC Charlotte
# Southern Illinois (point to carbondale)