#Note: delete extra ~empty rows from ecoevo_jobs before importing
#Note: save-as UTF-8 csv before importing

setwd("./ecoevo_jobs/")
jobs <- read.csv("ecoevojobs_2023_04_04.csv", stringsAsFactors = F, header = T,
                 strip.white = TRUE, fileEncoding = "UTF-8")

#Read in Carnegie data sheet
# Downloaded from: https://carnegieclassifications.iu.edu/downloads.php
carnegie <- read.csv("carnegie_2018.csv", stringsAsFactors = F)

#Label R1 & R2 schools
carnegie$insti_ranking <- "Other"
carnegie$insti_ranking[carnegie$BASIC2018 == 15] <- "R1" #R1 schools coded as 15 in 2018 dataset
carnegie$insti_ranking[carnegie$BASIC2018 == 16] <- "R2" #R2 schools coded as 16 in 2018 dataset

##TODO: add state matching for same-name schools, like Marian University
##      or Wheaton College

#Pull in the school insti_rankings into the Jobs sheet
jobs$insti_ranking <- carnegie$insti_ranking[match(jobs$Institution, carnegie$NAME)]

#Flag international schools
jobs$insti_ranking[!jobs$Location %in% 
                     c(state.name, "District of Columbia", "USA")] <-
  "International"

#Check that international flags don't have any false positives
table(jobs$Location[jobs$insti_ranking == "International"])

#Print institutions with no successful match 
unique(jobs$Institution[is.na(jobs$insti_ranking)])

#Rules to add for incomplete matching
#Treat "The" from beginning of Carnegie as optional
#Treat " at " anywhere in Carnegie as optional
#Carnegie uses "-" with no spaces, ecoevo sometimes uses ", " or " " or " - "

#Change all "St" and "St." to be "Saint" for matching as well

names_mod <- trimws(gsub("^The |, | at |-| - ", " ",
                         gsub("St |St\\. ", "Saint ", carnegie$NAME)))
insti_mod <- trimws(gsub("^The |, | at |-| - ", " ",
                         gsub("St |St\\. ", "Saint ", jobs$Institution)))

##Do partial matching
#Save the partially matched names to enable double-checking
jobs$matched_insti <- NA
jobs$matched_insti[is.na(jobs$insti_ranking)] <- 
  carnegie$NAME[match(insti_mod[is.na(jobs$insti_ranking)], names_mod)]

#Save the rankings with partial matching
jobs$insti_ranking[is.na(jobs$insti_ranking)] <- 
  carnegie$insti_ranking[match(insti_mod[is.na(jobs$insti_ranking)], names_mod)]

unmatched_names <- unique(jobs$Institution[is.na(jobs$insti_ranking)])

#Update manually-curated aliases list
#Original alias list generated by running:
# aliases <- data.frame("ecoevo_names" = unmatched_names, 
#                       "carnegie_names" = NA, "checked" = "N")
aliases <- read.csv("aliases.csv", fileEncoding = "Windows-1252")
if(any(!unmatched_names %in% aliases$ecoevo_names)) {
  aliases <- 
    rbind(aliases,
          data.frame(
            "ecoevo_names" = 
              unmatched_names[!unmatched_names %in% aliases$ecoevo_names],
            "carnegie_names" = NA, "checked" = "N"))
}
aliases <- aliases[order(aliases$ecoevo_names), ]
write.csv(x = aliases, file = "aliases.csv", row.names = FALSE,
          fileEncoding = "Windows-1252")
#Update then save as UTF-8

#Match using aliases     
myrows <- which(is.na(jobs$insti_ranking))
jobs$insti_ranking[myrows] <- 
  carnegie$insti_ranking[
    match(
      x = aliases$carnegie_names[
        match(jobs$Institution[myrows], aliases$ecoevo_names)],
      table = carnegie$NAME)]

write.csv(jobs, "jobs_withrankings.csv", row.names = FALSE)

##Old code below:


#Note: some schools will need aliases, bc carnegie lists them as
# with a name when they are the main campus (e.g. U of M is
# "University of Minnesota-Twin Cites")



# #For non-exact matches, find closest named university
# jobs$matched_insti <- NA
# for (row in which(is.na(jobs$insti_ranking))) {
#   state <- state.abb[match(jobs$Location[row], state.name)]
#   jobs$matched_insti[row] <- carnegie$NAME[which(carnegie$STABBR == state)][
#     stringdist::amatch(method = "lcs",
#       jobs$Institution[row],
#       carnegie$NAME[which(carnegie$STABBR == state)], 
#       maxDist = 20)]
# }
# 
# #Still struggling to find good weights that will be happy to drop endings
# carnegie$NAME[which(carnegie$STABBR == "OR")]
# stringdist::stringdist("Oregon State",
#                        "Oregon State University",
#                        weight = c(d = .001, i = .1, s = .1, t = 1))
# stringdist::stringdist("Oregon State",
#                        "Reed College",
#                        weight = c(d = .001, i = .1, s = .1, t = 1))
# carnegie$NAME[which(carnegie$STABBR == "OR")][stringdist::amatch("Oregon State",
#                    carnegie$NAME[which(carnegie$STABBR == "OR")],
#                        weight = c(d = .001, i = .1, s = .1, t = 1),
#                    maxDist = 100)]

##TODO: adjust non-exact matching to weight deletions (from the ecoevo list string)
##       to be 0 penalty

# 
# jobs$stringdist <- NA
# for (row in which(is.na(jobs$insti_ranking))) {
#   jobs$matched_insti[row] <- carnegie$NAME[
#     stringdist::amatch(jobs$Institution[row], carnegie$NAME, maxDist = 20)]
# }

# tail(unique(jobs$Institution[is.na(jobs$insti_ranking)]), 15)
# 
# table(jobs$Location[is.na(jobs$insti_ranking)])
# table(jobs$Rank)
# 
# write.csv(jobs, file = "jobs_output.csv", row.names = F)


#Add in aliases
# aliases <- c("MIT" = "Massachusetts Institute of Technology",
#              "UT Austin" =
#              
# 
# cutoffs <- c("Cal State" = "California State University",
#              "UMass" = "University of Massachusetts",


# MIT
# Cal State Fullerton
# UMass Boston
# UT Austin
# University of North Carolina
# UCLA
# University of Washington (point to Seattle)
# Western Colorado University
# The Ohio State University (point to main campus)
# NC State University
# UC Davis
# UCSB
# UNC Charlotte
# Southern Illinois (point to carbondale)