name: r2u

on:
  push:
  pull_request:
  release:

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: rocker/r2u:latest
    steps:
      - uses: actions/checkout@v3
      - name: Package Dependencies
        run: R -q -e 'remotes::install_deps(".", dependencies=TRUE)'
      # - name: Build Package
      #   run: R CMD build --no-build-vignettes --no-manual .
      # - name: Check Package
      #   run: R CMD check --no-vignettes --no-manual $(ls -1tr *.tar.gz | tail -1)
      - name: Run script
        run: Rscript -e 'source("R/ecoevo_jobs_analysis.R")'
        
